//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Paint1.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_HTML_NEWGAMEDLG             103
#define IDR_MAINFRAME                   128
#define IDR_Paint1TYPE                  129
#define IDS_ERR_READ                    129
#define IDS_ERR_EOF                     130
#define IDS_ERR_MAP_CREATE              131
#define IDB_LAND                        132
#define IDS_ERR_NOACCESS                132
#define IDS_ERR_OPEN                    132
#define IDB_SEA                         134
#define IDB_MASK                        145
#define IDB_UNDISCOVERED                147
#define IDB_BITMAP1                     150
#define IDB_UNDISCOVERED_MASK           150
#define IDB_COASTAL_MASK                151
#define IDB_COASTAL                     152
#define IDB_LAND_TERRAIN_TYPES          153
#define IDB_TERR_BLEND_MASK             154
#define IDB_MOUNTAINS                   162
#define IDB_MOUNTAINS_MASK              163
#define IDB_FORESTS                     164
#define IDB_FORESTS_MASK                165
#define IDB_HILLS                       166
#define IDB_HILLS_MASK                  167
#define IDB_BACKGROUND                  168
#define IDB_MNRIVERS                    169
#define IDB_MNRIVERS_MASK               170
#define IDB_COASTAL_RIVER               171
#define IDB_COASTAL_RIVER_MASK          172
#define ID_TEST_HIDE_UNEXPLORED         173
#define ID_TEST_NEWMAP                  174
#define IDD_NEW_RAND_MAP                175
#define IDB_PIECES                      176
#define IDB_BITMAP3                     177
#define IDB_PIECES_MASK                 177
#define IDB_PIECES_COLORS               180
#define IDB_BIG_PIECES_MASK             184
#define IDB_BITMAP2                     187
#define IDB_BITMAP5                     189
#define IDD_GAME_OPTS_DLG               190
#define ID_ACTIONS_ENDTURN              191
#define ID_FILE_GAMEOPTIONS             192
#define ID_TEST_ADDPIECE                194
#define IDD_ADD_PIECE                   195
#define ID_TEST_ACTIVATETIMER           196
#define ID_VIEW_ACTIVEPIECE             197
#define ID_HELP_ENCYCLOPEDIA            200
#define ID_ENCYCLOPEDIA_PIECES          201
#define ID_TEST_SYNCH                   202
#define ID_ACTIONS_SKIP                 203
#define ID_ACTIONS_WAIT                 204
#define IDD_CONFIRM_ATTACK              205
#define IDB_NEW_COLONY                  206
#define ID_TEST_PIECEANIMATE            207
#define ID_PIECEANIMATE_INCREASE        208
#define ID_PIECEANIMATE_DECREASE        209
#define IDD_RESOLVE_ATTACK              210
#define IDB_JANSSON_MAP                 213
#define IDB_MNRIVERS_OCEAN              214
#define IDD_COL_MSGBOX                  215
#define IDB_TAG_TEXT                    216
#define ID_ACTIONS_DISBAND              217
#define ID_ACTIONS_SLEEP                218
#define IDD_NEW_GAME_DLG                219
#define ID_TEST_DISPLAYMAPSTATISTICS    220
#define IDD_MAP_STATS                   221
#define ID_TEST_DISPLAYMAPSTATISTIC     223
#define IDC_NM_WIDTH_SLIDER             1004
#define IDC_NM_WIDTH_STATIC1            1005
#define IDC_NM_WIDTH_EDIT               1006
#define IDC_NM_HEIGHT_SLIDER            1007
#define IDC_NM_HEIGHT_STATIC            1008
#define IDC_NM_HEIGHT_EDIT              1009
#define IDC_NM_SIZE_STATIC              1013
#define IDC_NM_TEMP_SLIDER              1014
#define IDC_AUTO_END_TURN               1014
#define IDC_NM_CLIMATE_TEMP_STATIC      1015
#define IDC_NM_CLIMATE_TEMP_EDIT        1016
#define IDC_NM_RAIN_SLIDER              1017
#define IDC_NM_HEIGHT_STATIC2           1018
#define IDC_NM_WIDTH_EDIT4              1019
#define IDC_SCREEN_RES                  1019
#define IDC_NM_CLIMATE_STATIC           1020
#define IDC_EDIT_X                      1022
#define IDC_EDIT_Y                      1023
#define IDC_EDIT_TYPE                   1024
#define IDC_EDIT_OWNER                  1025
#define IDC_GO_ANIMATE_PIECE_MOVES      1025
#define IDC_DIALOG_QUESTION             1026
#define IDC_DIALOG_OK                   1027
#define IDC_ATTACK_PIECE                1028
#define IDC_STATIC_TITLE                1030
#define IDC_DEFEND_PIECE                1031
#define IDC_NM_CONTSIZE_SLIDER          1035
#define IDC_NM_CONTSIZE_STATIC          1036
#define IDC_NM_CONTSIZE_EDIT            1037
#define IDC_NM_ALTITIDE_SLIDER          1038
#define IDC_NM_ALTITUDE_STATIC          1039
#define IDC_NM_ALTITUDE_EDIT            1040
#define IDC_NM_LANDMASS_STATIC          1041
#define IDC_DLG_TITLE                   1042
#define IDC_RADIO1                      1043
#define IDC_NONE                        1043
#define IDC_RADIO2                      1044
#define IDC_ALTITUDE                    1044
#define IDC_RADIO3                      1045
#define IDC_TERRAIN_TYPE                1045
#define IDC_NM_CONTSIZE_SLIDER2         1049
#define IDC_NM_LANDPTS_SLIDER           1049
#define IDC_NM_LANDPTS_STATIC           1050
#define IDC_NM_LANDPTS_EDIT             1051
#define IDS_ERR_INVALID                 61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
